export const users = [
  { name: "Alice", age: 25 },
  { name: "Bob", age: 32 },
  { name: "Charlie", age: 41 },
  { name: "David", age: 19 },
  { name: "Emily", age: 28 },
  { name: "Frank", age: 55 },
  { name: "Grace", age: 37 },
  { name: "Henry", age: 22 },
  { name: "Ivy", age: 30 },
  { name: "Jack", age: 48 },
  { name: "Katie", age: 21 },
  { name: "Liam", age: 36 },
  { name: "Mia", age: 29 },
  { name: "Noah", age: 43 },
  { name: "Olivia", age: 24 },
  { name: "Peter", age: 39 },
  { name: "Quinn", age: 27 },
  { name: "Ryan", age: 51 },
  { name: "Sophia", age: 33 },
  { name: "Tom", age: 26 },
];
